2023-03-22 10:56:57,132 INFO    MainThread:6356 [wandb_setup.py:_flush():76] Configure stats pid to 6356
2023-03-22 10:56:57,132 INFO    MainThread:6356 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Administrator\.config\wandb\settings
2023-03-22 10:56:57,132 INFO    MainThread:6356 [wandb_setup.py:_flush():76] Loading settings from D:\d2l-zh\pytorch\object_detection\yolov5-7.0-SeaDronesSee\wandb\settings
2023-03-22 10:56:57,132 INFO    MainThread:6356 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-03-22 10:56:57,132 INFO    MainThread:6356 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': 'd:\\d2l-zh\\pytorch\\object_detection\\yolov5-7.0-SeaDronesSee\\train.py'}
2023-03-22 10:56:57,132 INFO    MainThread:6356 [wandb_setup.py:_flush():76] Applying login settings: {'login_timeout': 30}
2023-03-22 10:56:57,134 INFO    MainThread:6356 [wandb_init.py:_log_setup():506] Logging user logs to D:\d2l-zh\pytorch\object_detection\yolov5-7.0-SeaDronesSee\wandb\run-20230322_105657-0kl68k09\logs\debug.log
2023-03-22 10:56:57,134 INFO    MainThread:6356 [wandb_init.py:_log_setup():507] Logging internal logs to D:\d2l-zh\pytorch\object_detection\yolov5-7.0-SeaDronesSee\wandb\run-20230322_105657-0kl68k09\logs\debug-internal.log
2023-03-22 10:56:57,134 INFO    MainThread:6356 [wandb_init.py:init():546] calling init triggers
2023-03-22 10:56:57,134 INFO    MainThread:6356 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {'weights': 'runs\\train\\exp12\\weights\\last.pt', 'cfg': '', 'data': 'data\\SeaDronesSee.yaml', 'hyp': {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0, 'copy_paste': 0.0}, 'epochs': 200, 'batch_size': 64, 'imgsz': 640, 'rect': False, 'resume': False, 'nosave': False, 'noval': False, 'noautoanchor': False, 'noplots': False, 'evolve': None, 'bucket': '', 'cache': False, 'image_weights': False, 'device': '', 'multi_scale': False, 'single_cls': False, 'optimizer': 'SGD', 'sync_bn': False, 'workers': 8, 'project': 'runs\\train', 'name': 'exp', 'exist_ok': False, 'quad': False, 'cos_lr': False, 'label_smoothing': 0.0, 'patience': 100, 'freeze': [0], 'save_period': -1, 'seed': 0, 'local_rank': -1, 'entity': None, 'upload_dataset': False, 'bbox_interval': -1, 'artifact_alias': 'latest', 'save_dir': 'runs\\train\\exp13'}
2023-03-22 10:56:57,134 INFO    MainThread:6356 [wandb_init.py:init():602] starting backend
2023-03-22 10:56:57,134 INFO    MainThread:6356 [wandb_init.py:init():606] setting up manager
2023-03-22 10:56:57,136 INFO    MainThread:6356 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-03-22 10:56:57,138 INFO    MainThread:6356 [wandb_init.py:init():613] backend started and connected
2023-03-22 10:56:57,140 INFO    MainThread:6356 [wandb_init.py:init():701] updated telemetry
2023-03-22 10:56:57,141 INFO    MainThread:6356 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2023-03-22 10:57:57,591 ERROR   MainThread:6356 [wandb_init.py:init():755] backend process timed out, exiting...
encountered error: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-03-22 10:57:57,605 ERROR   MainThread:6356 [wandb_init.py:init():1171] error
Traceback (most recent call last):
  File "D:\Anaconda3\envs\d2l\lib\site-packages\wandb\sdk\wandb_init.py", line 1144, in init
    run = wi.init()
  File "D:\Anaconda3\envs\d2l\lib\site-packages\wandb\sdk\wandb_init.py", line 773, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
